services:
  nginx:
    image: cheftory/cheftory-nginx-gateway-dev:latest
    container_name: cheftory-gateway-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    environment:
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - cheftory_network

networks:
  cheftory_network:
    name: dev_cheftory_network
    driver: bridge
