name: cheftory nginx gateway CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 다른 아키텍처(arm64) 빌드를 위한 QEMU 설정
      - name: Set up QEMU
        # 멀티 아키텍처 빌드용 Buildx 설정
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # arm64로 빌드 (t4g)
      - name: Build and Push Docker image (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-prod:latest
          platforms: linux/arm64

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH to EC2 and create folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p cheftory-gateway

      - name: Copy docker-compose.prod.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0

      - name: Copy default.prod.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "default.prod.conf"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0

      - name: Copy nginx.prod.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx.prod.conf"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0

      - name: Create .env on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cheftory-gateway
            cat <<EOF > .env
            GEOIPUPDATE_ACCOUNT_ID=${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}
            GEOIPUPDATE_LICENSE_KEY=${{ secrets.GEOIPUPDATE_LICENSE_KEY }}
            EOF

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd cheftory-gateway

            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            sed -i "s|image: cheftory-nginx-gateway-prod:latest|image: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-prod:latest|g" docker-compose.prod.yml
            sed -i "s|image: cheftory-proxy-server-prod:latest|image: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-proxy-server-prod:latest|g" docker-compose.prod.yml

            sudo docker-compose -f docker-compose.prod.yml stop || true
            sudo docker-compose -f docker-compose.prod.yml rm -f || true
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-prod:latest || true
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-proxy-server-prod:latest || true

            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml up -d
