name: cheftory nginx gateway CI/CD Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev

jobs:
  build:
    environment: develop
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-dev:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-dev:latest

  deploy:
    environment: develop
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH to EC2 and create folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p cheftory-gateway

      - name: Copy docker-compose.dev.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.dev.yml"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0

      - name: Copy default.dev.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "default.dev.conf"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0
          
      - name: Copy nginx.dev.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx.dev.conf"
          target: "/home/ubuntu/cheftory-gateway/"
          strip_components: 0
      
      - name: Create .env on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cheftory-gateway
            cat <<EOF > .env
            GEOIPUPDATE_ACCOUNT_ID=${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}
            GEOIPUPDATE_LICENSE_KEY=${{ secrets.GEOIPUPDATE_LICENSE_KEY }}
            EOF

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd cheftory-gateway

            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            sed -i "s|image: cheftory-nginx-gateway-dev:latest|image: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-dev:latest|g" docker-compose.dev.yml
            sed -i "s|image: cheftory-proxy-server-dev:latest|image: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-proxy-server-dev:latest|g" docker-compose.dev.yml

            sudo docker-compose -f docker-compose.dev.yml stop || true
            sudo docker-compose -f docker-compose.dev.yml rm -f || true
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-nginx-gateway-dev:latest || true
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-proxy-server-dev:latest || true

            sudo docker-compose -f docker-compose.dev.yml pull
            sudo docker-compose -f docker-compose.dev.yml up -d
